server:
  port: 9001
dubbo: 
  scan: 
    basePackages: com.jt     #包扫描dubbo的service的注解
  application:  
    name: provider-user     #提供者服务的名称
  registry:            #链接zookeeper
    address: zookeeper://192.168.21.130:2181?backup=192.168.21.130:2182,192.168.21.130:2183 